function parseCookieString(str) {
  return String(str || '')
    .split(';')
    .map((s) => s.trim())
    .filter(Boolean)
    .map((kv) => {
      const i = kv.indexOf('=');
      if (i < 0) return null;
      return { name: kv.slice(0, i).trim(), value: kv.slice(i + 1).trim() };
    })
    .filter(Boolean);
}

function cookieHeader(account) {
  if (account.cookie) return String(account.cookie);
  const list = account.cookies || [];
  return list.map((c) => `${c.name}=${c.value}`).join('; ');
}

const SESSION_HTTPONLY = new Set(['c_user', 'xs', 'datr', 'sb', 'fr']);

function toCdpCookies(account) {
  const exp = Math.floor(Date.now() / 1000) + 90 * 24 * 3600;
  const raw = account.cookies && account.cookies.length
    ? account.cookies
    : parseCookieString(account.cookie);
  const out = [];
  for (const c of raw) {
    if (!c || !c.name) continue;
    const expires = c.expires && Number(c.expires) > Date.now() / 1000
      ? Math.floor(c.expires)
      : exp;
    const domain = c.domain && /facebook|messenger/i.test(c.domain)
      ? c.domain
      : '.facebook.com';
    out.push({
      name: c.name,
      value: String(c.value == null ? '' : c.value),
      domain,
      path: c.path || '/',
      secure: c.secure !== false,
      httpOnly: c.httpOnly != null ? !!c.httpOnly : SESSION_HTTPONLY.has(c.name),
      expires
    });
  }
  return out;
}

function toNetscape(account) {
  const exp = Math.floor(Date.now() / 1000) + 90 * 24 * 3600;
  const pairs = account.cookies && account.cookies.length
    ? account.cookies.map((c) => ({
        domain: c.domain || '.facebook.com',
        path: c.path || '/',
        secure: c.secure !== false,
        expires: c.expires > 0 ? Math.floor(c.expires) : exp,
        name: c.name,
        value: c.value
      }))
    : parseCookieString(account.cookie).map((c) => ({
        domain: '.facebook.com',
        path: '/',
        secure: true,
        expires: exp,
        name: c.name,
        value: c.value
      }));

  const lines = [
    '# Netscape HTTP Cookie File',
    '# Generated by FB Manager',
    ''
  ];
  for (const c of pairs) {
    const domain = c.domain.startsWith('.') ? c.domain : '.' + c.domain.replace(/^\./, '');
    lines.push([
      domain,
      'TRUE',
      c.path || '/',
      c.secure ? 'TRUE' : 'FALSE',
      String(c.expires || exp),
      c.name,
      c.value
    ].join('\t'));
  }
  return lines.join('\n') + (pairs.length ? '\n' : '');
}

function toJson(account) {
  return JSON.stringify({
    uid: account.uid || '',
    name: account.name || '',
    password: account.password || '',
    twoFa: account.twoFa || '',
    cookie: cookieHeader(account),
    cookies: account.cookies || parseCookieString(account.cookie),
    email: account.email || '',
    passmail: account.passmail || '',
    userAgent: account.userAgent || '',
    status: account.status || '',
    cookieDate: account.cookieDate || ''
  }, null, 2);
}

function cookiesOnly(accounts) {
  return (accounts || []).map(cookieHeader).filter(Boolean).join('\n');
}

function fmtDate(iso) {
  if (!iso) return '';
  const d = new Date(iso);
  if (Number.isNaN(d.getTime())) return '';
  const p = (n) => String(n).padStart(2, '0');
  return `${p(d.getDate())}/${p(d.getMonth() + 1)}/${d.getFullYear()} ${p(d.getHours())}:${p(d.getMinutes())}:${p(d.getSeconds())}`;
}

module.exports = { parseCookieString, cookieHeader, toCdpCookies, toNetscape, toJson, cookiesOnly, fmtDate };
